# Site settings
title: Craig Lawrence Derington
description: Senior Full Stack Engineer
url: "localhost:3000, craigderington.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Craig Derington
user_description: Veteran Web Developer automating the world with Docker, Python, Celery and MQtt.
user_title: Senior Full Stack Engineer
email: craigderington@pm.me
github_username:  craigderington

exclude: ['package.json', 'src' , 'node_modules']
