# Site settings
title: Craig Lawrence Derington
description: Disorder from Chaos
url: "localhost:3000, craigderington.github.io" # the base hostname

# User settings
username: Craig Derington
user_description: Veteran. Nerd. Nihilist. Nomad. 
user_title: Question Everything
email: craigderington@pm.me
github_username:  craigderington

exclude: ['package.json', 'src' , 'node_modules']
