# Site settings
title: Craig Lawrence Derington
description: "Veteran Web Developer & Database Engineer"
url: "localhost:3000, craigderington.github.io" # the base hostname

# User settings
username: Craig Derington
user_description: Disabled Veteran. Java &amp; Python Developer, Automation Expert
user_title: "Veteran Web Developer"
email: craigderington17@gmail.com
github_username:  craigderington

exclude: ['package.json', 'src' , 'node_modules']
