# Site settings
title: Craig Lawrence Derington
description: Senior Full Stack Engineer
url: "localhost:3000, craigderington.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Craig Derington
user_description: U.S. Army Armorer & Veteran, Python Developer, Crypto & Self-Sovereign Advocate.  Vires in Numeris.
user_title: Senior Full Stack Engineer
email: craigderington@protonmail.com
twitter_username: JamesCraigLND
github_username:  craigderington
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
