# Site settings
title: Craig Lawrence Derington
description: "Veteran web developer automating the world with Docker, Python & Celery."
url: "localhost:3000, craigderington.github.io" # the base hostname

# User settings
username: Craig Derington
user_description: "Veteran web developer automating the world with Docker, Python & Celery."
user_title: "There is no spoon..."
email: craig@craigderington.dev
github_username:  craigderington

exclude: ['package.json', 'src' , 'node_modules']
