# Site settings
title: Craig Lawrence Derington
description: "Ephesians 6:13"
url: "localhost:3000, craigderington.github.io" # the base hostname

# User settings
username: Craig Derington
user_description: Christian. Disabled Veteran. Python Developer. Foodie.
user_title: "Ephesians 6:13"
email: craigderington17@gmail.com
github_username:  craigderington

exclude: ['package.json', 'src' , 'node_modules']
