# Site settings
title: Craig Lawrence Derington
description: Question Everything
url: "localhost:3000, craigderington.github.io" # the base hostname

# User settings
username: Craig Derington
user_description: Veteran. Nerd. Nomad. Everything is a conspiracy.
user_title: Question Everything
email: craigderington@pm.me
github_username:  craigderington

exclude: ['package.json', 'src' , 'node_modules']
